#!/usr/bin/env bash
# configures a new ubuntu server as follows:
#	- set X-Served-By header
#	- restart server
sed -i "/server_name _;/ a\\\tadd_header X-Served-By \"\$HOSTNAME\";" /etc/nginx/sites-available/default
service nginx restart
